FROM python:3.12.5-alpine3.20 AS build

COPY ./src/requirements.txt ./requirements.txt

RUN pip install --upgrade pip
RUN pip install --user -r ./requirements.txt


FROM python:3.12.5-alpine3.20 AS prod

COPY --from=build /root/.local /root/.local

WORKDIR /flask-app

ENV PATH=/root/.local/bin:$PATH
ENV MESSAGE="Hello from Docker!"

COPY ./src .

CMD [ "python3", "-m", "flask", "run", "--host=0.0.0.0" ]
